# Generated by Django 5.2 on 2024-09-04 14:26

import lamindb.ids
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinicore", "0002_biosample_patient_biosample_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uid",
            field=models.CharField(
                default=lamindb.ids.base62_12, max_length=12, unique=True
            ),
        ),
    ]
